"""
Example: Using the PDF Generator MCP Server

This example demonstrates how to use the PDF Generator MCP client to generate PDF reports.
"""

import asyncio
import base64
from fastmcp import Client


async def main():
    """Run PDF Generator examples."""
    print("=== PDF Generator MCP Server Example ===\n")
    
    # Connect to the server
    async with Client("src/mcp_servers/pdf-generator/server.py") as client:
        # List available tools
        tools = await client.list_tools()
        print(f"Available tools: {[tool.name for tool in tools]}\n")
        
        tenant_id = "example-tenant"
        
        # Register tenant (optional - can also use default)
        print(f"=== Registering tenant: {tenant_id} ===")
        result = await client.call_tool(
            "register_tenant",
            {
                "tenant_id": tenant_id,
            },
        )
        print(f"Result: {result.content[0].text}\n")
        
        # Example 1: Generate PDF with base64 return format
        print(f"=== Generating PDF (base64 format) for tenant: {tenant_id} ===")
        
        template = """
        <!DOCTYPE html>
        <html>
        <head>
            <title>Report</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                h1 { color: #333; }
                .header { background-color: #f0f0f0; padding: 20px; margin-bottom: 20px; }
                .content { line-height: 1.6; }
                .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{{title}}</h1>
                <p>Generated on: {{date}}</p>
            </div>
            <div class="content">
                <h2>Report Details</h2>
                <p><strong>Customer:</strong> {{customer_name}}</p>
                <p><strong>Order ID:</strong> {{order_id}}</p>
                <p><strong>Amount:</strong> ${{amount}}</p>
                <p><strong>Status:</strong> {{status}}</p>
            </div>
            <div class="footer">
                <p>This is an automated report generated by the PDF Generator MCP Server.</p>
            </div>
        </body>
        </html>
        """
        
        content = {
            "title": "Order Report",
            "date": "2024-12-31",
            "customer_name": "John Doe",
            "order_id": "ORD-12345",
            "amount": "1,234.56",
            "status": "Completed"
        }
        
        result = await client.call_tool(
            "generate_pdf",
            {
                "tenant_id": tenant_id,
                "template": template,
                "content": content,
                "filename": "order_report.pdf",
                "return_format": "base64"
            },
        )
        
        result_data = eval(result.content[0].text)  # Parse JSON response
        print(f"Success: {result_data.get('success')}")
        print(f"Filename: {result_data.get('filename')}")
        print(f"Size: {result_data.get('size_bytes')} bytes (base64)")
        print(f"Message: {result_data.get('message')}\n")
        
        # Save the PDF to a file
        if result_data.get('success') and result_data.get('data'):
            pdf_data = base64.b64decode(result_data['data'])
            with open('generated_report.pdf', 'wb') as f:
                f.write(pdf_data)
            print("✅ PDF saved to 'generated_report.pdf'\n")
        
        # Example 2: Generate PDF with URL return format
        print(f"=== Generating PDF (URL format) for tenant: {tenant_id} ===")
        result = await client.call_tool(
            "generate_pdf",
            {
                "tenant_id": tenant_id,
                "template": template,
                "content": {
                    **content,
                    "title": "Invoice Report",
                    "order_id": "INV-67890"
                },
                "filename": "invoice_report.pdf",
                "return_format": "url"
            },
        )
        
        result_data = eval(result.content[0].text)
        print(f"Success: {result_data.get('success')}")
        if result_data.get('url'):
            print(f"URL: {result_data.get('url')}")
            print(f"File ID: {result_data.get('file_id')}")
            print(f"Expires at: {result_data.get('expires_at')}\n")


if __name__ == "__main__":
    asyncio.run(main())

